import { useState } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { PageHeader } from '@/components/common/PageHeader';
import { EmptyState } from '@/components/common/EmptyState';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Skeleton } from '@/components/ui/skeleton';
import {
    Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from '@/components/ui/select';
import {
    Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from '@/components/ui/table';
import { CalendarCheck, Users, GraduationCap, IndianRupee, BookOpen, Download, FileText, Loader2, Filter } from 'lucide-react';
import { useClasses } from '@/hooks/useStudents';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { formatCurrencyINR, formatDateIndian } from '@/lib/dateUtils';
import { format, parseISO } from 'date-fns';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { useSchoolName } from '@/hooks/useSettings';
import { useAuth } from '@/contexts/AuthContext';
import { useAdminActionLogger } from '@/hooks/useAdminActionLogger';

function TableSkeleton() {
    return (
        <div className="space-y-3 p-4">
            {Array.from({ length: 5 }).map((_, i) => (
                <div key={i} className="flex gap-4">
                    <Skeleton className="h-10 flex-1" />
                    <Skeleton className="h-10 w-24" />
                    <Skeleton className="h-10 w-20" />
                </div>
            ))}
        </div>
    );
}

// ─── Generic Excel Export ──────────────────────
function exportToExcel(data: any[][], headers: string[], filename: string, meta: { schoolName: string; title: string; generatedBy: string }) {
    const wsData: any[][] = [];
    wsData.push([meta.schoolName]);
    wsData.push([meta.title]);
    wsData.push([`Generated by: ${meta.generatedBy}`, '', `Generated on: ${format(new Date(), 'dd/MM/yyyy hh:mm a')}`]);
    wsData.push([]);
    wsData.push(headers);
    data.forEach(row => wsData.push(row));

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(wsData);
    ws['!cols'] = headers.map(() => ({ wch: 18 }));
    XLSX.utils.book_append_sheet(wb, ws, 'Report');
    XLSX.writeFile(wb, `${filename}.xlsx`);
}

function exportToPDF(headers: string[], body: string[][], filename: string, meta: { schoolName: string; title: string; generatedBy: string }) {
    const doc = new jsPDF({ orientation: headers.length > 6 ? 'landscape' : 'portrait', unit: 'mm', format: 'a4' });
    const w = doc.internal.pageSize.getWidth();

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(meta.schoolName, w / 2, 15, { align: 'center' });
    doc.setFontSize(12);
    doc.text(meta.title, w / 2, 22, { align: 'center' });
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated by: ${meta.generatedBy} | ${format(new Date(), 'dd/MM/yyyy hh:mm a')}`, w / 2, 28, { align: 'center' });

    autoTable(doc, {
        head: [headers],
        body,
        startY: 33,
        theme: 'striped',
        headStyles: { fillColor: [59, 130, 246], fontSize: 8 },
        bodyStyles: { fontSize: 7 },
        styles: { cellPadding: 2 },
    });

    doc.save(`${filename}.pdf`);
}

// ═══════ ATTENDANCE REPORTS ═══════
function AttendanceReport({ schoolName, generatedBy }: { schoolName: string; generatedBy: string }) {
    const { classes } = useClasses();
    const [classFilter, setClassFilter] = useState('all');
    const [dateFrom, setDateFrom] = useState(new Date().toISOString().split('T')[0]);
    const [dateTo, setDateTo] = useState(new Date().toISOString().split('T')[0]);

    const { data, isLoading } = useQuery({
        queryKey: ['report-attendance', classFilter, dateFrom, dateTo],
        queryFn: async () => {
            let query = supabase
                .from('student_attendance')
                .select('date, status, students(full_name, classes(name, section))')
                .gte('date', dateFrom)
                .lte('date', dateTo);
            if (classFilter !== 'all') query = query.eq('class_id', classFilter);
            const { data, error } = await query;
            if (error) throw error;
            return data as any[];
        },
    });

    const records = data || [];
    const present = records.filter(r => r.status === 'present').length;
    const absent = records.filter(r => r.status === 'absent').length;
    const total = records.length;
    const rate = total > 0 ? Math.round((present / total) * 100) : 0;

    const handleExportExcel = () => {
        const headers = ['Student Name', 'Class', 'Date', 'Status'];
        const rows = records.map(r => [
            r.students?.full_name || '-',
            `${r.students?.classes?.name || '-'} ${r.students?.classes?.section || ''}`,
            formatDateIndian(r.date),
            r.status,
        ]);
        exportToExcel(rows, headers, `Attendance_Report_${dateFrom}_to_${dateTo}`, { schoolName, title: 'Attendance Report', generatedBy });
    };

    const handleExportPDF = () => {
        const headers = ['Student Name', 'Class', 'Date', 'Status'];
        const rows = records.map(r => [
            r.students?.full_name || '-',
            `${r.students?.classes?.name || '-'} ${r.students?.classes?.section || ''}`,
            formatDateIndian(r.date),
            r.status,
        ]);
        exportToPDF(headers, rows, `Attendance_Report_${dateFrom}_to_${dateTo}`, { schoolName, title: 'Attendance Report', generatedBy });
    };

    return (
        <div className="space-y-4">
            <div className="glass-card p-4">
                <div className="flex flex-wrap items-center gap-3">
                    <Filter className="w-4 h-4 text-muted-foreground" />
                    <Select value={classFilter} onValueChange={setClassFilter}>
                        <SelectTrigger className="w-40"><SelectValue placeholder="All Classes" /></SelectTrigger>
                        <SelectContent>
                            <SelectItem value="all">All Classes</SelectItem>
                            {classes.map((c: any) => <SelectItem key={c.id} value={c.id}>{c.name} {c.section && `- ${c.section}`}</SelectItem>)}
                        </SelectContent>
                    </Select>
                    <Input type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)} className="w-40" />
                    <span className="text-sm text-muted-foreground">to</span>
                    <Input type="date" value={dateTo} onChange={e => setDateTo(e.target.value)} className="w-40" />
                    <div className="ml-auto flex gap-2">
                        <Button variant="outline" size="sm" onClick={handleExportExcel} className="gap-1"><Download className="w-3 h-3" /> Excel</Button>
                        <Button variant="outline" size="sm" onClick={handleExportPDF} className="gap-1"><Download className="w-3 h-3" /> PDF</Button>
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
                <div className="stat-card"><p className="text-2xl font-bold">{total}</p><p className="text-xs text-muted-foreground">Total Records</p></div>
                <div className="stat-card"><p className="text-2xl font-bold text-success">{present}</p><p className="text-xs text-muted-foreground">Present</p></div>
                <div className="stat-card"><p className="text-2xl font-bold text-destructive">{absent}</p><p className="text-xs text-muted-foreground">Absent</p></div>
                <div className="stat-card"><p className="text-2xl font-bold text-primary">{rate}%</p><p className="text-xs text-muted-foreground">Attendance Rate</p></div>
            </div>

            {isLoading ? <TableSkeleton /> : records.length === 0 ? (
                <EmptyState icon={CalendarCheck} title="No Records Found" description="No attendance records found for the selected filters" />
            ) : (
                <div className="glass-card overflow-hidden">
                    <div className="overflow-x-auto">
                        <Table>
                            <TableHeader><TableRow>
                                <TableHead>Student</TableHead><TableHead>Class</TableHead><TableHead>Date</TableHead><TableHead>Status</TableHead>
                            </TableRow></TableHeader>
                            <TableBody>
                                {records.slice(0, 100).map((r, i) => (
                                    <TableRow key={i} className="table-row-hover">
                                        <TableCell>{r.students?.full_name}</TableCell>
                                        <TableCell>{r.students?.classes?.name} {r.students?.classes?.section || ''}</TableCell>
                                        <TableCell>{formatDateIndian(r.date)}</TableCell>
                                        <TableCell>
                                            <span className={r.status === 'present' ? 'badge-success' : r.status === 'absent' ? 'badge-destructive' : 'badge-warning'}>
                                                {r.status}
                                            </span>
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </div>
                    {records.length > 100 && <p className="text-xs text-muted-foreground text-center py-2">Showing first 100 of {records.length} records. Export for full data.</p>}
                </div>
            )}
        </div>
    );
}

// ═══════ STUDENT REPORTS ═══════
function StudentReport({ schoolName, generatedBy }: { schoolName: string; generatedBy: string }) {
    const { data, isLoading } = useQuery({
        queryKey: ['report-students'],
        queryFn: async () => {
            const { data, error } = await supabase.from('students').select('*, classes(name, section)').eq('is_active', true).order('full_name');
            if (error) throw error;
            return data as any[];
        },
    });
    const students = data || [];

    const handleExportExcel = () => {
        const headers = ['Name', 'Admission No', 'Class', 'Gender', 'DOB', 'Parent', 'Phone'];
        const rows = students.map(s => [s.full_name, s.admission_number, `${s.classes?.name || '-'} ${s.classes?.section || ''}`, s.gender || '-', s.date_of_birth ? formatDateIndian(s.date_of_birth) : '-', s.parent_name || '-', s.parent_phone || '-']);
        exportToExcel(rows, headers, 'Student_Report', { schoolName, title: 'Student List Report', generatedBy });
    };

    return (
        <div className="space-y-4">
            <div className="flex justify-between items-center">
                <p className="text-sm text-muted-foreground">Total: {students.length} students</p>
                <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={handleExportExcel} className="gap-1"><Download className="w-3 h-3" /> Excel</Button>
                </div>
            </div>
            {isLoading ? <TableSkeleton /> : students.length === 0 ? (
                <EmptyState icon={GraduationCap} title="No Students" description="No student records found" />
            ) : (
                <div className="glass-card overflow-hidden">
                    <div className="overflow-x-auto">
                        <Table>
                            <TableHeader><TableRow>
                                <TableHead>Name</TableHead><TableHead>Adm. No</TableHead><TableHead>Class</TableHead><TableHead>Gender</TableHead><TableHead>DOB</TableHead><TableHead>Parent</TableHead>
                            </TableRow></TableHeader>
                            <TableBody>
                                {students.slice(0, 100).map(s => (
                                    <TableRow key={s.id} className="table-row-hover">
                                        <TableCell className="font-medium">{s.full_name}</TableCell>
                                        <TableCell>{s.admission_number}</TableCell>
                                        <TableCell>{s.classes?.name} {s.classes?.section || ''}</TableCell>
                                        <TableCell>{s.gender || '-'}</TableCell>
                                        <TableCell>{s.date_of_birth ? formatDateIndian(s.date_of_birth) : '-'}</TableCell>
                                        <TableCell>{s.parent_name || '-'}</TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </div>
                </div>
            )}
        </div>
    );
}

// ═══════ STAFF REPORTS ═══════
function StaffReport({ schoolName, generatedBy }: { schoolName: string; generatedBy: string }) {
    const { data, isLoading } = useQuery({
        queryKey: ['report-staff'],
        queryFn: async () => {
            // employees table has full_name directly — no profile join needed
            const { data, error } = await (supabase as any)
                .from('employees')
                .select('id, full_name, designation, department, employee_type, contact_number, status, date_of_joining')
                .order('full_name');
            if (error) throw error;
            return data as any[];
        },
    });
    const staff = data || [];
    const teachingCount = staff.filter((s: any) => s.employee_type === 'Teaching').length;
    const nonTeachingCount = staff.filter((s: any) => s.employee_type !== 'Teaching').length;

    const handleExportExcel = () => {
        const headers = ['Name', 'Designation', 'Department', 'Type', 'Contact', 'Status', 'Joining Date'];
        const rows = staff.map((s: any) => [
            s.full_name || '-',
            s.designation || '-',
            s.department || '-',
            s.employee_type || '-',
            s.contact_number || '-',
            s.status || '-',
            s.date_of_joining ? formatDateIndian(s.date_of_joining) : '-',
        ]);
        exportToExcel(rows, headers, 'Staff_Report', { schoolName, title: 'Staff Report', generatedBy });
    };

    const handleExportPDF = () => {
        const headers = ['Name', 'Designation', 'Department', 'Type', 'Status'];
        const rows = staff.map((s: any) => [
            s.full_name || '-', s.designation || '-', s.department || '-', s.employee_type || '-', s.status || '-',
        ]);
        exportToPDF(headers, rows, 'Staff_Report', { schoolName, title: 'Staff Report', generatedBy });
    };

    return (
        <div className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="stat-card"><p className="text-2xl font-bold">{staff.length}</p><p className="text-xs text-muted-foreground">Total Staff</p></div>
                <div className="stat-card"><p className="text-2xl font-bold text-primary">{teachingCount}</p><p className="text-xs text-muted-foreground">Teaching</p></div>
                <div className="stat-card"><p className="text-2xl font-bold" style={{color:'var(--warning)'}}>{nonTeachingCount}</p><p className="text-xs text-muted-foreground">Non-Teaching</p></div>
            </div>
            <div className="flex justify-between items-center">
                <p className="text-sm text-muted-foreground">Total: {staff.length} staff members</p>
                <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={handleExportExcel} className="gap-1"><Download className="w-3 h-3" /> Excel</Button>
                    <Button variant="outline" size="sm" onClick={handleExportPDF} className="gap-1"><FileText className="w-3 h-3" /> PDF</Button>
                </div>
            </div>
            {isLoading ? <TableSkeleton /> : staff.length === 0 ? (
                <EmptyState icon={Users} title="No Staff Records" description="No staff records found" />
            ) : (
                <div className="glass-card overflow-hidden">
                    <div className="overflow-x-auto">
                        <Table>
                            <TableHeader><TableRow>
                                <TableHead>Name</TableHead><TableHead>Designation</TableHead><TableHead>Department</TableHead><TableHead>Type</TableHead><TableHead>Status</TableHead>
                            </TableRow></TableHeader>
                            <TableBody>
                                {staff.slice(0, 100).map((s: any) => (
                                    <TableRow key={s.id} className="table-row-hover">
                                        <TableCell className="font-medium">{s.full_name || '-'}</TableCell>
                                        <TableCell>{s.designation || '-'}</TableCell>
                                        <TableCell>{s.department || '-'}</TableCell>
                                        <TableCell><span className={s.employee_type === 'Teaching' ? 'badge-primary' : 'badge-warning'}>{s.employee_type || '-'}</span></TableCell>
                                        <TableCell><span className={s.status === 'Active' ? 'badge-success' : 'badge-destructive'}>{s.status || '-'}</span></TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </div>
                    {staff.length > 100 && <p className="text-xs text-muted-foreground text-center py-2">Showing first 100 of {staff.length} records. Export for full data.</p>}
                </div>
            )}
        </div>
    );
}

// ═══════ FEE REPORTS ═══════
function FeeReport({ schoolName, generatedBy }: { schoolName: string; generatedBy: string }) {
    const { data, isLoading } = useQuery({
        queryKey: ['report-fees'],
        queryFn: async () => {
            const { data, error } = await (supabase as any)
                .from('student_fees')
                .select('*, students(full_name, classes(name, section)), fee_structures(fee_categories(category_name))');
            if (error) throw error;
            return data as any[];
        },
    });
    const fees = data || [];
    const totalCollected = fees.reduce((s: number, f: any) => s + (f.paid_amount || 0), 0);
    const totalOutstanding = fees.reduce((s: number, f: any) => s + (f.balance_amount || 0), 0);

    return (
        <div className="space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="stat-card"><p className="text-2xl font-bold text-success">{formatCurrencyINR(totalCollected)}</p><p className="text-xs text-muted-foreground">Total Collected</p></div>
                <div className="stat-card"><p className="text-2xl font-bold text-destructive">{formatCurrencyINR(totalOutstanding)}</p><p className="text-xs text-muted-foreground">Outstanding</p></div>
                <div className="stat-card"><p className="text-2xl font-bold">{fees.length}</p><p className="text-xs text-muted-foreground">Total Records</p></div>
            </div>
            {isLoading ? <TableSkeleton /> : fees.length === 0 ? (
                <EmptyState icon={IndianRupee} title="No Fee Records" description="No fee records found" />
            ) : (
                <div className="glass-card overflow-hidden">
                    <div className="overflow-x-auto">
                        <Table>
                            <TableHeader><TableRow>
                                <TableHead>Student</TableHead><TableHead>Class</TableHead><TableHead>Total</TableHead><TableHead>Paid</TableHead><TableHead>Balance</TableHead><TableHead>Status</TableHead>
                            </TableRow></TableHeader>
                            <TableBody>
                                {fees.slice(0, 100).map((f: any) => (
                                    <TableRow key={f.id} className="table-row-hover">
                                        <TableCell className="font-medium">{f.students?.full_name}</TableCell>
                                        <TableCell>{f.students?.classes?.name} {f.students?.classes?.section || ''}</TableCell>
                                        <TableCell>{formatCurrencyINR(f.total_amount)}</TableCell>
                                        <TableCell className="text-success">{formatCurrencyINR(f.paid_amount)}</TableCell>
                                        <TableCell className="text-destructive">{formatCurrencyINR(f.balance_amount)}</TableCell>
                                        <TableCell>
                                            <span className={f.status === 'Paid' ? 'badge-success' : f.status === 'Partial' ? 'badge-warning' : 'badge-destructive'}>{f.status}</span>
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </div>
                </div>
            )}
        </div>
    );
}

// ═══════ HOMEWORK & REMARKS REPORTS ═══════
function HomeworkReport({ schoolName, generatedBy }: { schoolName: string; generatedBy: string }) {
    const { data, isLoading } = useQuery({
        queryKey: ['report-homework'],
        queryFn: async () => {
            const { data, error } = await supabase.from('homework').select('*, classes(name, section)').order('due_date', { ascending: false }).limit(200);
            if (error) throw error;
            return data as any[];
        },
    });
    const homework = data || [];

    return (
        <div className="space-y-4">
            <div className="stat-card"><p className="text-2xl font-bold">{homework.length}</p><p className="text-xs text-muted-foreground">Total Homework Assigned</p></div>
            {isLoading ? <TableSkeleton /> : homework.length === 0 ? (
                <EmptyState icon={BookOpen} title="No Homework" description="No homework records found" />
            ) : (
                <div className="glass-card overflow-hidden">
                    <div className="overflow-x-auto">
                        <Table>
                            <TableHeader><TableRow>
                                <TableHead>Title</TableHead><TableHead>Subject</TableHead><TableHead>Class</TableHead><TableHead>Due Date</TableHead>
                            </TableRow></TableHeader>
                            <TableBody>
                                {homework.slice(0, 100).map(h => (
                                    <TableRow key={h.id} className="table-row-hover">
                                        <TableCell className="font-medium">{h.title}</TableCell>
                                        <TableCell>{h.subject}</TableCell>
                                        <TableCell>{h.classes?.name} {h.classes?.section || ''}</TableCell>
                                        <TableCell>{formatDateIndian(h.due_date)}</TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </div>
                </div>
            )}
        </div>
    );
}

// ═══════ MAIN REPORTS PAGE ═══════
export default function Reports() {
    const schoolName = useSchoolName();
    const { profile, role } = useAuth();
    const { logAction } = useAdminActionLogger();
    const generatedBy = `${profile?.fullName || 'Admin'} (${role || 'admin'})`;

    return (
        <div className="space-y-6">
            <PageHeader
                title="Reports"
                description="Generate and export comprehensive school reports"
                breadcrumbs={[{ label: 'Dashboard', href: '/dashboard' }, { label: 'Reports' }]}
            />

            <Tabs defaultValue="attendance" className="animate-fade-up" style={{ animationDelay: '100ms' }}>
                <TabsList className="grid w-full grid-cols-5">
                    <TabsTrigger value="attendance" className="gap-1 text-xs"><CalendarCheck className="w-3.5 h-3.5" /> Attendance</TabsTrigger>
                    <TabsTrigger value="students" className="gap-1 text-xs"><GraduationCap className="w-3.5 h-3.5" /> Students</TabsTrigger>
                    <TabsTrigger value="staff" className="gap-1 text-xs"><Users className="w-3.5 h-3.5" /> Staff</TabsTrigger>
                    <TabsTrigger value="fees" className="gap-1 text-xs"><IndianRupee className="w-3.5 h-3.5" /> Fees</TabsTrigger>
                    <TabsTrigger value="homework" className="gap-1 text-xs"><BookOpen className="w-3.5 h-3.5" /> Homework</TabsTrigger>
                </TabsList>

                <TabsContent value="attendance"><AttendanceReport schoolName={schoolName} generatedBy={generatedBy} /></TabsContent>
                <TabsContent value="students"><StudentReport schoolName={schoolName} generatedBy={generatedBy} /></TabsContent>
                <TabsContent value="staff"><StaffReport schoolName={schoolName} generatedBy={generatedBy} /></TabsContent>
                <TabsContent value="fees"><FeeReport schoolName={schoolName} generatedBy={generatedBy} /></TabsContent>
                <TabsContent value="homework"><HomeworkReport schoolName={schoolName} generatedBy={generatedBy} /></TabsContent>
            </Tabs>
        </div>
    );
}
